### ISSUE TITLE
Add API surface to obtain data field appearance info

### ISSUE THREAD

**Issue by valterc** [hammerheadnav/karoo-ext#10]
Hi, looks like there is no way to obtain details such as:

- Data field alignment
- In Ride Appearance (light/dark)

Is that the case?

For custom (graphical) DataTypes it would be great if that information would be available, perhaps in the [ViewConfig](https://github.com/hammerheadnav/karoo-ext/blob/master/lib/src/main/kotlin/io/hammerhead/karooext/models/ViewConfig.kt) which already contains the `textSize`.

One extra question is around the `In Ride Appearance` in auto mode, when the change happens, are the DataTypes recreated and `startView` invoked again or is the theming applied to existing views?

Thank you.

**Comment by brentnd** [comment]
In-ride appearance is done with standard Android night mode. [getNightMode()](https://developer.android.com/reference/android/app/UiModeManager#getNightMode()) can be used if you need to know the state programmatically, otherwise, night-specific resources (i.e. `res/values-night/colors.xml`) will be used.

When the user's preference is auto, the change happens by KOS setting night mode on `UiModeManager` which results in the entire context and views being reconstructed.

Data field alignment is a good one to add and, as you suggest, makes sense in `ViewConfig`.

**Comment by brentnd** [comment]
Good question @timklge. Not right now.

Extension data types have a value for editor of 42 but the custom view elements are displayed.
